import axios from "axios";
import { useAPI } from "../src/axios/useAPI";
import Head from "next/head";
import { useEffect, useState } from "react";
//백이랑 연결 잘 되어 있는 지 테스트...
export default function Home() {
  const [hello, setHello] = useState();
  const { get } = useAPI();
  /*useEffect(() => {//sse test
    const eventSource = new EventSource(
      "http://localhost:8080/api/test/notice?userId=1"
    );

    eventSource.onmessage = (event) => {
      console.log("New event received:", event.data);
      setHello(event.data); // 수신된 데이터를 상태에 저장
    };

    eventSource.onerror = (error) => {
      console.log("EventSource error:", error);
      eventSource.close(); // 오류 발생 시 연결 종료
    };

    return () => {
      eventSource.close(); // 컴포넌트 언마운트 시 연결 해제
    };
  }, []);*/
  useEffect(() => {
    const fetchData = async () => {
      try {
        const result = await get("/hello");
        setHello(result);
      } catch (error) {
        console.error("데이터 가져오기 실패:", error);
      }
    };

    fetchData();
  }, [get]);
  return (
    <>
      <Head>
        <title>LCW 프로젝트 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>페이지 테스트</div>
      <div>로컬백앤드에서 보내온 데이터입니다. {hello}</div>
    </>
  );
}
