import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
//백이랑 연결 잘 되어 있는 지 테스트...
export default function Home() {
  const [hello, setHello] = useState("되니");

  useEffect(() => {
    axios
      .get("http://localhost:8080/api/jw")
      .then((response) => setHello(response.data))
      .catch((error) => console.log(error));
  }, []);
  return (
    <>
      <Head>
        <title>LCW 프로젝트 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>페이지 테스트</div>
      <div>로컬백앤드에서 보내온 데이터입니다. {hello}</div>
    </>
  );
}
